DELETE FROM VAGA_CARACTERISTICAS WHERE id = 1;

DELETE FROM RESERVA_VAGAS WHERE id = 1;

DELETE FROM PAGAMENTOS WHERE id = 1;

DELETE FROM VAGAS WHERE id = 1;

DELETE FROM CARACTERISTICAS WHERE id = 1;

DELETE FROM RESERVAS WHERE id = 1;

DELETE FROM CLIENTES WHERE id = 1;

DELETE FROM QUARTOS WHERE id = 1;