-- TUDO
SELECT * FROM CLIENTES;
SELECT * FROM QUARTOS;
SELECT * FROM VAGAS;
SELECT * FROM CARACTERISTICAS;
SELECT * FROM VAGA_CARACTERISTICAS;
SELECT * FROM RESERVAS;
SELECT * FROM RESERVA_VAGAS;
SELECT * FROM PAGAMENTOS;

-- ÚNICO
SELECT * FROM CLIENTES WHERE id = 1;
SELECT * FROM QUARTOS WHERE id = 1;
SELECT * FROM VAGAS WHERE id = 1;
SELECT * FROM CARACTERISTICAS WHERE id = 1;
SELECT * FROM VAGA_CARACTERISTICAS WHERE id = 1;
SELECT * FROM RESERVAS WHERE id = 1;
SELECT * FROM RESERVA_VAGAS WHERE id = 1;
SELECT * FROM PAGAMENTOS WHERE id = 1;